import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

export default function CountrySelect() {
  return (
    <Autocomplete
      id="country-select-demo"
      options={countries}
      fullWidth
      getOptionLabel={(option) => `${option.label}`}
      renderOption={(props, option) => {
        const { key, ...optionProps } = props;
        return (
          <Box
            key={key}
            component="li"
            sx={{ "& > img": { mr: 2, flexShrink: 0, maxWidth: 275 } }}
            {...optionProps}
          >
            <img
              loading="lazy"
              width="20"
              srcSet={`https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x`}
              src={`https://flagcdn.com/w20/${option.code.toLowerCase()}.png`}
              alt=""
            />
            {option.label} ({option.code})
          </Box>
        );
      }}
      renderInput={(params) => (
        <TextField
          {...params}
          label="Country"
          slotProps={{
            htmlInput: {
              ...params.inputProps,
              autoComplete: "new-password",
            },
          }}
        />
      )}
    />
  );
}
interface CountryType {
  code: string;
  label: string;
  suggested?: boolean;
  flag: string;
}
// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const countries: readonly CountryType[] = [
  { code: "AD", label: "Andorra", flag: "https://flagcdn.com/ad.svg" },
  {
    code: "AE",
    label: "United Arab Emirates",
    flag: "https://flagcdn.com/ae.svg",
  },
  { code: "AF", label: "Afghanistan", flag: "https://flagcdn.com/af.svg" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    flag: "https://flagcdn.com/ag.svg",
  },
  { code: "AI", label: "Anguilla", flag: "https://flagcdn.com/ai.svg" },
  { code: "AL", label: "Albania", flag: "https://flagcdn.com/al.svg" },
  { code: "AM", label: "Armenia", flag: "https://flagcdn.com/am.svg" },
  { code: "AO", label: "Angola", flag: "https://flagcdn.com/ao.svg" },
  { code: "AQ", label: "Antarctica", flag: "https://flagcdn.com/aq.svg" },
  { code: "AR", label: "Argentina", flag: "https://flagcdn.com/ar.svg" },
  { code: "AS", label: "American Samoa", flag: "https://flagcdn.com/as.svg" },
  { code: "AT", label: "Austria", flag: "https://flagcdn.com/at.svg" },
  { code: "AU", label: "Australia", flag: "https://flagcdn.com/au.svg" },
  { code: "AW", label: "Aruba", flag: "https://flagcdn.com/aw.svg" },
  { code: "AX", label: "Åland Islands", flag: "https://flagcdn.com/ax.svg" },
  { code: "AZ", label: "Azerbaijan", flag: "https://flagcdn.com/az.svg" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/ba.svg",
  },
  { code: "BB", label: "Barbados", flag: "https://flagcdn.com/bb.svg" },
  { code: "BD", label: "Bangladesh", flag: "https://flagcdn.com/bd.svg" },
  { code: "BE", label: "Belgium", flag: "https://flagcdn.com/be.svg" },
  { code: "BF", label: "Burkina Faso", flag: "https://flagcdn.com/bf.svg" },
  { code: "BG", label: "Bulgaria", flag: "https://flagcdn.com/bg.svg" },
  { code: "BH", label: "Bahrain", flag: "https://flagcdn.com/bh.svg" },
  { code: "BI", label: "Burundi", flag: "https://flagcdn.com/bi.svg" },
  { code: "BJ", label: "Benin", flag: "https://flagcdn.com/bj.svg" },
  { code: "BL", label: "Saint Barthélemy", flag: "https://flagcdn.com/bl.svg" },
  { code: "BM", label: "Bermuda", flag: "https://flagcdn.com/bm.svg" },
  {
    code: "BN",
    label: "Brunei Darussalam",
    flag: "https://flagcdn.com/bn.svg",
  },
  { code: "BO", label: "Bolivia", flag: "https://flagcdn.com/bo.svg" },
  { code: "BR", label: "Brazil", flag: "https://flagcdn.com/br.svg" },
  { code: "BS", label: "Bahamas", flag: "https://flagcdn.com/bs.svg" },
  { code: "BT", label: "Bhutan", flag: "https://flagcdn.com/bt.svg" },
  { code: "BV", label: "Bouvet Island", flag: "https://flagcdn.com/bv.svg" },
  { code: "BW", label: "Botswana", flag: "https://flagcdn.com/bw.svg" },
  { code: "BY", label: "Belarus", flag: "https://flagcdn.com/by.svg" },
  { code: "BZ", label: "Belize", flag: "https://flagcdn.com/bz.svg" },
  { code: "CA", label: "Canada", flag: "https://flagcdn.com/ca.svg" },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    flag: "https://flagcdn.com/cc.svg",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    flag: "https://flagcdn.com/cd.svg",
  },
  {
    code: "CF",
    label: "Central African Republic",
    flag: "https://flagcdn.com/cf.svg",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    flag: "https://flagcdn.com/cg.svg",
  },
  { code: "CH", label: "Switzerland", flag: "https://flagcdn.com/ch.svg" },
  { code: "CI", label: "Côte d'Ivoire", flag: "https://flagcdn.com/ci.svg" },
  { code: "CK", label: "Cook Islands", flag: "https://flagcdn.com/ck.svg" },
  { code: "CL", label: "Chile", flag: "https://flagcdn.com/cl.svg" },
  { code: "CM", label: "Cameroon", flag: "https://flagcdn.com/cm.svg" },
  { code: "CN", label: "China", flag: "https://flagcdn.com/cn.svg" },
  { code: "CO", label: "Colombia", flag: "https://flagcdn.com/co.svg" },
  { code: "CR", label: "Costa Rica", flag: "https://flagcdn.com/cr.svg" },
  { code: "CU", label: "Cuba", flag: "https://flagcdn.com/cu.svg" },
  { code: "CV", label: "Cape Verde", flag: "https://flagcdn.com/cv.svg" },
  { code: "CW", label: "Curaçao", flag: "https://flagcdn.com/cw.svg" },
  { code: "CX", label: "Christmas Island", flag: "https://flagcdn.com/cx.svg" },
  { code: "CY", label: "Cyprus", flag: "https://flagcdn.com/cy.svg" },
  { code: "CZ", label: "Czech Republic", flag: "https://flagcdn.com/cz.svg" },
  { code: "DE", label: "Germany", flag: "https://flagcdn.com/de.svg" },
  { code: "DJ", label: "Djibouti", flag: "https://flagcdn.com/dj.svg" },
  { code: "DK", label: "Denmark", flag: "https://flagcdn.com/dk.svg" },
  { code: "DM", label: "Dominica", flag: "https://flagcdn.com/dm.svg" },
  {
    code: "DO",
    label: "Dominican Republic",
    flag: "https://flagcdn.com/do.svg",
  },
  { code: "DZ", label: "Algeria", flag: "https://flagcdn.com/dz.svg" },
  { code: "EC", label: "Ecuador", flag: "https://flagcdn.com/ec.svg" },
  { code: "EE", label: "Estonia", flag: "https://flagcdn.com/ee.svg" },
  { code: "EG", label: "Egypt", flag: "https://flagcdn.com/eg.svg" },
  { code: "EH", label: "Western Sahara", flag: "https://flagcdn.com/eh.svg" },
  { code: "ER", label: "Eritrea", flag: "https://flagcdn.com/er.svg" },
  { code: "ES", label: "Spain", flag: "https://flagcdn.com/es.svg" },
  { code: "ET", label: "Ethiopia", flag: "https://flagcdn.com/et.svg" },
  { code: "FI", label: "Finland", flag: "https://flagcdn.com/fi.svg" },
  { code: "FJ", label: "Fiji", flag: "https://flagcdn.com/fj.svg" },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    flag: "https://flagcdn.com/fm.svg",
  },
  { code: "FO", label: "Faroe Islands", flag: "https://flagcdn.com/fo.svg" },
  { code: "FR", label: "France", flag: "https://flagcdn.com/fr.svg" },
  { code: "GA", label: "Gabon", flag: "https://flagcdn.com/ga.svg" },
  { code: "GB", label: "United Kingdom", flag: "https://flagcdn.com/gb.svg" },
  { code: "GD", label: "Grenada", flag: "https://flagcdn.com/gd.svg" },
  { code: "GE", label: "Georgia", flag: "https://flagcdn.com/ge.svg" },
  { code: "GF", label: "French Guiana", flag: "https://flagcdn.com/gf.svg" },
  { code: "GG", label: "Guernsey", flag: "https://flagcdn.com/gg.svg" },
  { code: "GH", label: "Ghana", flag: "https://flagcdn.com/gh.svg" },
  { code: "GI", label: "Gibraltar", flag: "https://flagcdn.com/gi.svg" },
  { code: "GL", label: "Greenland", flag: "https://flagcdn.com/gl.svg" },
  { code: "GM", label: "Gambia", flag: "https://flagcdn.com/gm.svg" },
  { code: "GN", label: "Guinea", flag: "https://flagcdn.com/gn.svg" },
  { code: "GP", label: "Guadeloupe", flag: "https://flagcdn.com/gp.svg" },
  {
    code: "GQ",
    label: "Equatorial Guinea",
    flag: "https://flagcdn.com/gq.svg",
  },
  { code: "GR", label: "Greece", flag: "https://flagcdn.com/gr.svg" },
  { code: "GT", label: "Guatemala", flag: "https://flagcdn.com/gt.svg" },
  { code: "GU", label: "Guam", flag: "https://flagcdn.com/gu.svg" },
  { code: "GW", label: "Guinea-Bissau", flag: "https://flagcdn.com/gw.svg" },
  { code: "GY", label: "Guyana", flag: "https://flagcdn.com/gy.svg" },
  { code: "HK", label: "Hong Kong", flag: "https://flagcdn.com/hk.svg" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    flag: "https://flagcdn.com/hm.svg",
  },
  { code: "HN", label: "Honduras", flag: "https://flagcdn.com/hn.svg" },
  { code: "HR", label: "Croatia", flag: "https://flagcdn.com/hr.svg" },
  { code: "HT", label: "Haiti", flag: "https://flagcdn.com/ht.svg" },
  { code: "HU", label: "Hungary", flag: "https://flagcdn.com/hu.svg" },
  { code: "ID", label: "Indonesia", flag: "https://flagcdn.com/id.svg" },
  { code: "IE", label: "Ireland", flag: "https://flagcdn.com/ie.svg" },
  { code: "IL", label: "Israel", flag: "https://flagcdn.com/il.svg" },
  { code: "IM", label: "Isle of Man", flag: "https://flagcdn.com/im.svg" },
  { code: "IN", label: "India", flag: "https://flagcdn.com/in.svg" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    flag: "https://flagcdn.com/io.svg",
  },
  { code: "IQ", label: "Iraq", flag: "https://flagcdn.com/iq.svg" },
  { code: "IR", label: "Iran", flag: "https://flagcdn.com/ir.svg" },
  { code: "IS", label: "Iceland", flag: "https://flagcdn.com/is.svg" },
  { code: "IT", label: "Italy", flag: "https://flagcdn.com/it.svg" },
  { code: "JE", label: "Jersey", flag: "https://flagcdn.com/je.svg" },
  { code: "JM", label: "Jamaica", flag: "https://flagcdn.com/jm.svg" },
  { code: "JO", label: "Jordan", flag: "https://flagcdn.com/jo.svg" },
  { code: "JP", label: "Japan", flag: "https://flagcdn.com/jp.svg" },
  { code: "KE", label: "Kenya", flag: "https://flagcdn.com/ke.svg" },
  { code: "KG", label: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg" },
  { code: "KH", label: "Cambodia", flag: "https://flagcdn.com/kh.svg" },
  { code: "KI", label: "Kiribati", flag: "https://flagcdn.com/ki.svg" },
  { code: "KM", label: "Comoros", flag: "https://flagcdn.com/km.svg" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/kn.svg",
  },
  { code: "KP", label: "North Korea", flag: "https://flagcdn.com/kp.svg" },
  { code: "KR", label: "South Korea", flag: "https://flagcdn.com/kr.svg" },
  { code: "KW", label: "Kuwait", flag: "https://flagcdn.com/kw.svg" },
  { code: "KY", label: "Cayman Islands", flag: "https://flagcdn.com/ky.svg" },
  { code: "KZ", label: "Kazakhstan", flag: "https://flagcdn.com/kz.svg" },
  { code: "LA", label: "Laos", flag: "https://flagcdn.com/la.svg" },
  { code: "LB", label: "Lebanon", flag: "https://flagcdn.com/lb.svg" },
  { code: "LC", label: "Saint Lucia", flag: "https://flagcdn.com/lc.svg" },
  { code: "LI", label: "Liechtenstein", flag: "https://flagcdn.com/li.svg" },
  { code: "LK", label: "Sri Lanka", flag: "https://flagcdn.com/lk.svg" },
  { code: "LR", label: "Liberia", flag: "https://flagcdn.com/lr.svg" },
  { code: "LS", label: "Lesotho", flag: "https://flagcdn.com/ls.svg" },
  { code: "LT", label: "Lithuania", flag: "https://flagcdn.com/lt.svg" },
  { code: "LU", label: "Luxembourg", flag: "https://flagcdn.com/lu.svg" },
  { code: "LV", label: "Latvia", flag: "https://flagcdn.com/lv.svg" },
  { code: "LY", label: "Libya", flag: "https://flagcdn.com/ly.svg" },
  { code: "MA", label: "Morocco", flag: "https://flagcdn.com/ma.svg" },
  { code: "MC", label: "Monaco", flag: "https://flagcdn.com/mc.svg" },
  { code: "MD", label: "Moldova", flag: "https://flagcdn.com/md.svg" },
  { code: "ME", label: "Montenegro", flag: "https://flagcdn.com/me.svg" },
  { code: "MF", label: "Saint Martin", flag: "https://flagcdn.com/mf.svg" },
  { code: "MG", label: "Madagascar", flag: "https://flagcdn.com/mg.svg" },
  { code: "MH", label: "Marshall Islands", flag: "https://flagcdn.com/mh.svg" },
  { code: "MK", label: "North Macedonia", flag: "https://flagcdn.com/mk.svg" },
  { code: "ML", label: "Mali", flag: "https://flagcdn.com/ml.svg" },
  { code: "MM", label: "Myanmar", flag: "https://flagcdn.com/mm.svg" },
  { code: "MN", label: "Mongolia", flag: "https://flagcdn.com/mn.svg" },
  { code: "MO", label: "Macao", flag: "https://flagcdn.com/mo.svg" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    flag: "https://flagcdn.com/mp.svg",
  },
  { code: "MQ", label: "Martinique", flag: "https://flagcdn.com/mq.svg" },
  { code: "MR", label: "Mauritania", flag: "https://flagcdn.com/mr.svg" },
  { code: "MS", label: "Montserrat", flag: "https://flagcdn.com/ms.svg" },
  { code: "MT", label: "Malta", flag: "https://flagcdn.com/mt.svg" },
  { code: "MU", label: "Mauritius", flag: "https://flagcdn.com/mu.svg" },
  { code: "MV", label: "Maldives", flag: "https://flagcdn.com/mv.svg" },
  { code: "MW", label: "Malawi", flag: "https://flagcdn.com/mw.svg" },
  { code: "MX", label: "Mexico", flag: "https://flagcdn.com/mx.svg" },
  { code: "MY", label: "Malaysia", flag: "https://flagcdn.com/my.svg" },
  { code: "MZ", label: "Mozambique", flag: "https://flagcdn.com/mz.svg" },
  { code: "NA", label: "Namibia", flag: "https://flagcdn.com/na.svg" },
  { code: "NC", label: "New Caledonia", flag: "https://flagcdn.com/nc.svg" },
  { code: "NE", label: "Niger", flag: "https://flagcdn.com/ne.svg" },
  { code: "NF", label: "Norfolk Island", flag: "https://flagcdn.com/nf.svg" },
  { code: "NG", label: "Nigeria", flag: "https://flagcdn.com/ng.svg" },
  { code: "NI", label: "Nicaragua", flag: "https://flagcdn.com/ni.svg" },
  { code: "NL", label: "Netherlands", flag: "https://flagcdn.com/nl.svg" },
  { code: "NO", label: "Norway", flag: "https://flagcdn.com/no.svg" },
  { code: "NP", label: "Nepal", flag: "https://flagcdn.com/np.svg" },
  { code: "NR", label: "Nauru", flag: "https://flagcdn.com/nr.svg" },
  { code: "NU", label: "Niue", flag: "https://flagcdn.com/nu.svg" },
  { code: "NZ", label: "New Zealand", flag: "https://flagcdn.com/nz.svg" },
  { code: "OM", label: "Oman", flag: "https://flagcdn.com/om.svg" },
  { code: "PA", label: "Panama", flag: "https://flagcdn.com/pa.svg" },
  { code: "PE", label: "Peru", flag: "https://flagcdn.com/pe.svg" },
  { code: "PF", label: "French Polynesia", flag: "https://flagcdn.com/pf.svg" },
  { code: "PG", label: "Papua New Guinea", flag: "https://flagcdn.com/pg.svg" },
  { code: "PH", label: "Philippines", flag: "https://flagcdn.com/ph.svg" },
  { code: "PK", label: "Pakistan", flag: "https://flagcdn.com/pk.svg" },
  { code: "PL", label: "Poland", flag: "https://flagcdn.com/pl.svg" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/pm.svg",
  },
  { code: "PN", label: "Pitcairn", flag: "https://flagcdn.com/pn.svg" },
  { code: "PR", label: "Puerto Rico", flag: "https://flagcdn.com/pr.svg" },
  { code: "PT", label: "Portugal", flag: "https://flagcdn.com/pt.svg" },
  { code: "PW", label: "Palau", flag: "https://flagcdn.com/pw.svg" },
  { code: "PY", label: "Paraguay", flag: "https://flagcdn.com/py.svg" },
  { code: "QA", label: "Qatar", flag: "https://flagcdn.com/qa.svg" },
  { code: "RE", label: "Réunion", flag: "https://flagcdn.com/re.svg" },
  { code: "RO", label: "Romania", flag: "https://flagcdn.com/ro.svg" },
  { code: "RS", label: "Serbia", flag: "https://flagcdn.com/rs.svg" },
  { code: "RU", label: "Russia", flag: "https://flagcdn.com/ru.svg" },
  { code: "RW", label: "Rwanda", flag: "https://flagcdn.com/rw.svg" },
  { code: "SA", label: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg" },
  { code: "SB", label: "Solomon Islands", flag: "https://flagcdn.com/sb.svg" },
  { code: "SC", label: "Seychelles", flag: "https://flagcdn.com/sc.svg" },
  { code: "SD", label: "Sudan", flag: "https://flagcdn.com/sd.svg" },
  { code: "SE", label: "Sweden", flag: "https://flagcdn.com/se.svg" },
  { code: "SG", label: "Singapore", flag: "https://flagcdn.com/sg.svg" },
  { code: "SH", label: "Saint Helena", flag: "https://flagcdn.com/sh.svg" },
  { code: "SI", label: "Slovenia", flag: "https://flagcdn.com/si.svg" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/sj.svg",
  },
  { code: "SK", label: "Slovakia", flag: "https://flagcdn.com/sk.svg" },
  { code: "SL", label: "Sierra Leone", flag: "https://flagcdn.com/sl.svg" },
  { code: "SM", label: "San Marino", flag: "https://flagcdn.com/sm.svg" },
  { code: "SN", label: "Senegal", flag: "https://flagcdn.com/sn.svg" },
  { code: "SO", label: "Somalia", flag: "https://flagcdn.com/so.svg" },
  { code: "SR", label: "Suriname", flag: "https://flagcdn.com/sr.svg" },
  { code: "SS", label: "South Sudan", flag: "https://flagcdn.com/ss.svg" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    flag: "https://flagcdn.com/st.svg",
  },
  { code: "SV", label: "El Salvador", flag: "https://flagcdn.com/sv.svg" },
  { code: "SX", label: "Sint Maarten", flag: "https://flagcdn.com/sx.svg" },
  { code: "SY", label: "Syria", flag: "https://flagcdn.com/sy.svg" },
  { code: "SZ", label: "Eswatini", flag: "https://flagcdn.com/sz.svg" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/tc.svg",
  },
  { code: "TD", label: "Chad", flag: "https://flagcdn.com/td.svg" },
  {
    code: "TF",
    label: "French Southern Territories",
    flag: "https://flagcdn.com/tf.svg",
  },
  { code: "TG", label: "Togo", flag: "https://flagcdn.com/tg.svg" },
  { code: "TH", label: "Thailand", flag: "https://flagcdn.com/th.svg" },
  { code: "TJ", label: "Tajikistan", flag: "https://flagcdn.com/tj.svg" },
  { code: "TK", label: "Tokelau", flag: "https://flagcdn.com/tk.svg" },
  { code: "TL", label: "Timor-Leste", flag: "https://flagcdn.com/tl.svg" },
  { code: "TM", label: "Turkmenistan", flag: "https://flagcdn.com/tm.svg" },
  { code: "TN", label: "Tunisia", flag: "https://flagcdn.com/tn.svg" },
  { code: "TO", label: "Tonga", flag: "https://flagcdn.com/to.svg" },
  { code: "TR", label: "Turkey", flag: "https://flagcdn.com/tr.svg" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    flag: "https://flagcdn.com/tt.svg",
  },
  { code: "TV", label: "Tuvalu", flag: "https://flagcdn.com/tv.svg" },
  { code: "TZ", label: "Tanzania", flag: "https://flagcdn.com/tz.svg" },
  { code: "UA", label: "Ukraine", flag: "https://flagcdn.com/ua.svg" },
  { code: "UG", label: "Uganda", flag: "https://flagcdn.com/ug.svg" },
  {
    code: "UM",
    label: "United States Minor Outlying Islands",
    flag: "https://flagcdn.com/um.svg",
  },
  {
    code: "US",
    label: "United States of America",
    flag: "https://flagcdn.com/us.svg",
  },
  { code: "UY", label: "Uruguay", flag: "https://flagcdn.com/uy.svg" },
  { code: "UZ", label: "Uzbekistan", flag: "https://flagcdn.com/uz.svg" },
  { code: "VA", label: "Vatican City", flag: "https://flagcdn.com/va.svg" },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/vc.svg",
  },
  { code: "VE", label: "Venezuela", flag: "https://flagcdn.com/ve.svg" },
  {
    code: "VG",
    label: "British Virgin Islands",
    flag: "https://flagcdn.com/vg.svg",
  },
  {
    code: "VI",
    label: "U.S. Virgin Islands",
    flag: "https://flagcdn.com/vi.svg",
  },
  { code: "VN", label: "Vietnam", flag: "https://flagcdn.com/vn.svg" },
  { code: "VU", label: "Vanuatu", flag: "https://flagcdn.com/vu.svg" },
  {
    code: "WF",
    label: "Wallis and Futuna",
    flag: "https://flagcdn.com/wf.svg",
  },
  { code: "WS", label: "Samoa", flag: "https://flagcdn.com/ws.svg" },
  { code: "YE", label: "Yemen", flag: "https://flagcdn.com/ye.svg" },
  { code: "YT", label: "Mayotte", flag: "https://flagcdn.com/yt.svg" },
  { code: "ZA", label: "South Africa", flag: "https://flagcdn.com/za.svg" },
  { code: "ZM", label: "Zambia", flag: "https://flagcdn.com/zm.svg" },
  { code: "ZW", label: "Zimbabwe", flag: "https://flagcdn.com/zw.svg" },
];
